--Table - Column meata stored in mySQL hive metastore
use hive;

select
T.TBL_ID, T.TBL_NAME,
C.COLUMN_NAME, C.CD_ID, C.INTEGER_IDX, C.TYPE_NAME, C.COMMENT
from
  TBLS as T
  join SDS S on T.SD_ID=S.SD_ID
  join COLUMNS_V2 C on S.CD_ID=C.CD_ID

select
CS.DB_NAME, CS.TBL_ID, CS.TABLE_NAME, CS.COLUMN_NAME, CS.COLUMN_TYPE,
CS.NUM_NULLS, CS.NUM_DISTINCTS, CS.AVG_COL_LEN, CS.MAX_COL_LEN,
CONCAT (IFNULL (LONG_LOW_VALUE,''), IFNULL (DOUBLE_LOW_VALUE,''), IFNULL (BIG_DECIMAL_LOW_VALUE,'')) as LOW_VALUE,
CONCAT (IFNULL (LONG_HIGH_VALUE,''), IFNULL (DOUBLE_HIGH_VALUE,''), IFNULL (BIG_DECIMAL_HIGH_VALUE,'')) as HIGH_VALUE,
CS.LAST_ANALYZED
From TAB_COL_STATS CS
